# Generated by Django 3.0.8 on 2020-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], default='group', max_length=15),
        ),
    ]
